// Code generated by storj.io/dotworld. DO NOT EDIT.

package reference

import (
	"image"

	"storj.io/dotworld"
)

var worldMap = &dotworld.Map{
	CountX: 64,
	CountY: 26,
	Grid: &dotworld.Grid{
		CountX:    64,
		Threshold: 0.20000000298023224,
		Coord:     dotworld.PlateCarre{Width: 8192, Height: 4096},
	},
	Bounds: image.Rectangle{
		Min: image.Point{X: 0, Y: 100},
		Max: image.Point{X: 8192, Y: 3385},
	},
	Locations: map[dotworld.GridPosition]*dotworld.Location{
		{Row: 0, Col: 15}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -92.8125},
			Land: 0.20220351219177246,
			Load: 0,
		},
		{Row: 0, Col: 16}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -87.1875},
			Land: 0.30244284868240356,
			Load: 0,
		},
		{Row: 0, Col: 17}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -81.5625},
			Land: 0.4273490309715271,
			Load: 0,
		},
		{Row: 0, Col: 18}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -75.9375},
			Land: 0.5582461953163147,
			Load: 0,
		},
		{Row: 0, Col: 19}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -70.3125},
			Land: 0.4916841387748718,
			Load: 0,
		},
		{Row: 0, Col: 20}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -64.6875},
			Land: 0.3562837243080139,
			Load: 0,
		},
		{Row: 0, Col: 21}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -59.0625},
			Land: 0.35738956928253174,
			Load: 0,
		},
		{Row: 0, Col: 22}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -53.4375},
			Land: 0.3952646255493164,
			Load: 0,
		},
		{Row: 0, Col: 23}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -47.8125},
			Land: 0.4507189989089966,
			Load: 0,
		},
		{Row: 0, Col: 24}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -42.1875},
			Land: 0.5548519492149353,
			Load: 0,
		},
		{Row: 0, Col: 25}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -36.5625},
			Land: 0.6249030828475952,
			Load: 0,
		},
		{Row: 0, Col: 26}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -30.9375},
			Land: 0.6109203100204468,
			Load: 0,
		},
		{Row: 0, Col: 27}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -25.3125},
			Land: 0.5019469261169434,
			Load: 0,
		},
		{Row: 0, Col: 28}: {
			S2:   dotworld.S2{Lat: 82.79296875, Long: -19.6875},
			Land: 0.2803919315338135,
			Load: 0,
		},
		{Row: 1, Col: 11}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -115.3125},
			Land: 0.2937662601470947,
			Load: 0,
		},
		{Row: 1, Col: 12}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -109.6875},
			Land: 0.2940295934677124,
			Load: 0,
		},
		{Row: 1, Col: 13}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -104.0625},
			Land: 0.23841196298599243,
			Load: 0,
		},
		{Row: 1, Col: 14}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -98.4375},
			Land: 0.32437002658843994,
			Load: 0,
		},
		{Row: 1, Col: 15}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -92.8125},
			Land: 0.5245416164398193,
			Load: 0,
		},
		{Row: 1, Col: 16}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -87.1875},
			Land: 0.6395854949951172,
			Load: 0,
		},
		{Row: 1, Col: 17}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -81.5625},
			Land: 0.7614004015922546,
			Load: 0,
		},
		{Row: 1, Col: 18}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -75.9375},
			Land: 0.25933194160461426,
			Load: 0,
		},
		{Row: 1, Col: 19}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -70.3125},
			Land: 0.2986692190170288,
			Load: 0,
		},
		{Row: 1, Col: 20}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -64.6875},
			Land: 0.5991607904434204,
			Load: 0,
		},
		{Row: 1, Col: 21}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -59.0625},
			Land: 0.7886728048324585,
			Load: 0,
		},
		{Row: 1, Col: 22}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -53.4375},
			Land: 0.9997297525405884,
			Load: 0,
		},
		{Row: 1, Col: 23}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -47.8125},
			Land: 1,
			Load: 0,
		},
		{Row: 1, Col: 24}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -42.1875},
			Land: 1,
			Load: 0,
		},
		{Row: 1, Col: 25}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -36.5625},
			Land: 1,
			Load: 0,
		},
		{Row: 1, Col: 26}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -30.9375},
			Land: 1,
			Load: 0,
		},
		{Row: 1, Col: 27}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -25.3125},
			Land: 0.9994928240776062,
			Load: 0,
		},
		{Row: 1, Col: 28}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: -19.6875},
			Land: 0.4766864776611328,
			Load: 0,
		},
		{Row: 1, Col: 34}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 14.0625},
			Land: 0.3200501799583435,
			Load: 0,
		},
		{Row: 1, Col: 35}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 19.6875},
			Land: 0.28258752822875977,
			Load: 0,
		},
		{Row: 1, Col: 42}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 59.0625},
			Land: 0.20354986190795898,
			Load: 0,
		},
		{Row: 1, Col: 48}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 92.8125},
			Land: 0.344463050365448,
			Load: 0,
		},
		{Row: 1, Col: 49}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 98.4375},
			Land: 0.5138305425643921,
			Load: 0,
		},
		{Row: 1, Col: 50}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 104.0625},
			Land: 0.6384767889976501,
			Load: 0,
		},
		{Row: 1, Col: 51}: {
			S2:   dotworld.S2{Lat: 77.16796875, Long: 109.6875},
			Land: 0.4017532467842102,
			Load: 0,
		},
		{Row: 2, Col: 3}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -160.3125},
			Land: 0.3103039264678955,
			Load: 0,
		},
		{Row: 2, Col: 4}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -154.6875},
			Land: 0.3778298497200012,
			Load: 0,
		},
		{Row: 2, Col: 5}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -149.0625},
			Land: 0.2913219928741455,
			Load: 0,
		},
		{Row: 2, Col: 6}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -143.4375},
			Land: 0.22213470935821533,
			Load: 0,
		},
		{Row: 2, Col: 9}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -126.5625},
			Land: 0.2854992151260376,
			Load: 0,
		},
		{Row: 2, Col: 10}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -120.9375},
			Land: 0.6020256280899048,
			Load: 0,
		},
		{Row: 2, Col: 11}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -115.3125},
			Land: 0.6550788283348083,
			Load: 0,
		},
		{Row: 2, Col: 12}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -109.6875},
			Land: 0.648932933807373,
			Load: 0,
		},
		{Row: 2, Col: 13}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -104.0625},
			Land: 0.454198956489563,
			Load: 0,
		},
		{Row: 2, Col: 14}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -98.4375},
			Land: 0.41344040632247925,
			Load: 0,
		},
		{Row: 2, Col: 15}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -92.8125},
			Land: 0.5216152667999268,
			Load: 0,
		},
		{Row: 2, Col: 16}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -87.1875},
			Land: 0.529084324836731,
			Load: 0,
		},
		{Row: 2, Col: 17}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -81.5625},
			Land: 0.6954984664916992,
			Load: 0,
		},
		{Row: 2, Col: 18}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -75.9375},
			Land: 0.5791618824005127,
			Load: 0,
		},
		{Row: 2, Col: 19}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -70.3125},
			Land: 0.3602474331855774,
			Load: 0,
		},
		{Row: 2, Col: 22}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -53.4375},
			Land: 0.627160906791687,
			Load: 0,
		},
		{Row: 2, Col: 23}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -47.8125},
			Land: 0.9944352507591248,
			Load: 0,
		},
		{Row: 2, Col: 24}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -42.1875},
			Land: 1,
			Load: 0,
		},
		{Row: 2, Col: 25}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -36.5625},
			Land: 1,
			Load: 0,
		},
		{Row: 2, Col: 26}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -30.9375},
			Land: 0.994467556476593,
			Load: 0,
		},
		{Row: 2, Col: 27}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: -25.3125},
			Land: 0.7618446350097656,
			Load: 0,
		},
		{Row: 2, Col: 35}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 19.6875},
			Land: 0.20516908168792725,
			Load: 0,
		},
		{Row: 2, Col: 36}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 25.3125},
			Land: 0.35452568531036377,
			Load: 0,
		},
		{Row: 2, Col: 37}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 30.9375},
			Land: 0.23784035444259644,
			Load: 0,
		},
		{Row: 2, Col: 41}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 53.4375},
			Land: 0.32762783765792847,
			Load: 0,
		},
		{Row: 2, Col: 44}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 70.3125},
			Land: 0.597956657409668,
			Load: 0,
		},
		{Row: 2, Col: 45}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 75.9375},
			Land: 0.4845849275588989,
			Load: 0,
		},
		{Row: 2, Col: 46}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 81.5625},
			Land: 0.7375050187110901,
			Load: 0,
		},
		{Row: 2, Col: 47}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 87.1875},
			Land: 0.9291614294052124,
			Load: 0,
		},
		{Row: 2, Col: 48}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 92.8125},
			Land: 0.981052041053772,
			Load: 0,
		},
		{Row: 2, Col: 49}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 98.4375},
			Land: 0.9659656286239624,
			Load: 0,
		},
		{Row: 2, Col: 50}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 104.0625},
			Land: 0.9707155823707581,
			Load: 0,
		},
		{Row: 2, Col: 51}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 109.6875},
			Land: 0.9051678776741028,
			Load: 0,
		},
		{Row: 2, Col: 52}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 115.3125},
			Land: 0.8723400831222534,
			Load: 0,
		},
		{Row: 2, Col: 53}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 120.9375},
			Land: 0.7712376117706299,
			Load: 0,
		},
		{Row: 2, Col: 54}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 126.5625},
			Land: 0.7891237735748291,
			Load: 0,
		},
		{Row: 2, Col: 55}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 132.1875},
			Land: 0.4589053988456726,
			Load: 0,
		},
		{Row: 2, Col: 56}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 137.8125},
			Land: 0.5285670757293701,
			Load: 0,
		},
		{Row: 2, Col: 57}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 143.4375},
			Land: 0.7169010043144226,
			Load: 0,
		},
		{Row: 2, Col: 58}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 149.0625},
			Land: 0.5503726601600647,
			Load: 0,
		},
		{Row: 2, Col: 59}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 154.6875},
			Land: 0.38884228467941284,
			Load: 0,
		},
		{Row: 2, Col: 60}: {
			S2:   dotworld.S2{Lat: 71.54296875, Long: 160.3125},
			Land: 0.23882603645324707,
			Load: 0,
		},
		{Row: 3, Col: 0}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -177.1875},
			Land: 0.46910732984542847,
			Load: 0,
		},
		{Row: 3, Col: 1}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -171.5625},
			Land: 0.25849229097366333,
			Load: 0,
		},
		{Row: 3, Col: 2}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -165.9375},
			Land: 0.3184642195701599,
			Load: 0,
		},
		{Row: 3, Col: 3}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -160.3125},
			Land: 0.8558921813964844,
			Load: 0,
		},
		{Row: 3, Col: 4}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -154.6875},
			Land: 0.9854679107666016,
			Load: 0,
		},
		{Row: 3, Col: 5}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -149.0625},
			Land: 0.9852115511894226,
			Load: 0,
		},
		{Row: 3, Col: 6}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -143.4375},
			Land: 0.9847402572631836,
			Load: 0,
		},
		{Row: 3, Col: 7}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -137.8125},
			Land: 0.9868156909942627,
			Load: 0,
		},
		{Row: 3, Col: 8}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -132.1875},
			Land: 0.9686645269393921,
			Load: 0,
		},
		{Row: 3, Col: 9}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -126.5625},
			Land: 0.9396297931671143,
			Load: 0,
		},
		{Row: 3, Col: 10}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -120.9375},
			Land: 0.7900053262710571,
			Load: 0,
		},
		{Row: 3, Col: 11}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -115.3125},
			Land: 0.8502743244171143,
			Load: 0,
		},
		{Row: 3, Col: 12}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -109.6875},
			Land: 0.7778260707855225,
			Load: 0,
		},
		{Row: 3, Col: 13}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -104.0625},
			Land: 0.8501960039138794,
			Load: 0,
		},
		{Row: 3, Col: 14}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -98.4375},
			Land: 0.7799491286277771,
			Load: 0,
		},
		{Row: 3, Col: 15}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -92.8125},
			Land: 0.8875960111618042,
			Load: 0,
		},
		{Row: 3, Col: 16}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -87.1875},
			Land: 0.6620984077453613,
			Load: 0,
		},
		{Row: 3, Col: 17}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -81.5625},
			Land: 0.29932934045791626,
			Load: 0,
		},
		{Row: 3, Col: 18}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -75.9375},
			Land: 0.2874506711959839,
			Load: 0,
		},
		{Row: 3, Col: 19}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -70.3125},
			Land: 0.8404636979103088,
			Load: 0,
		},
		{Row: 3, Col: 20}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -64.6875},
			Land: 0.4965415596961975,
			Load: 0,
		},
		{Row: 3, Col: 22}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -53.4375},
			Land: 0.3357809782028198,
			Load: 0,
		},
		{Row: 3, Col: 23}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -47.8125},
			Land: 0.986210823059082,
			Load: 0,
		},
		{Row: 3, Col: 24}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -42.1875},
			Land: 0.9026216268539429,
			Load: 0,
		},
		{Row: 3, Col: 25}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -36.5625},
			Land: 0.47732675075531006,
			Load: 0,
		},
		{Row: 3, Col: 28}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: -19.6875},
			Land: 0.39584624767303467,
			Load: 0,
		},
		{Row: 3, Col: 34}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 14.0625},
			Land: 0.685761570930481,
			Load: 0,
		},
		{Row: 3, Col: 35}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 19.6875},
			Land: 0.842939555644989,
			Load: 0,
		},
		{Row: 3, Col: 36}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 25.3125},
			Land: 0.8443608283996582,
			Load: 0,
		},
		{Row: 3, Col: 37}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 30.9375},
			Land: 0.9106153249740601,
			Load: 0,
		},
		{Row: 3, Col: 38}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 36.5625},
			Land: 0.6818378567695618,
			Load: 0,
		},
		{Row: 3, Col: 39}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 42.1875},
			Land: 0.6635871529579163,
			Load: 0,
		},
		{Row: 3, Col: 40}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 47.8125},
			Land: 0.8001201748847961,
			Load: 0,
		},
		{Row: 3, Col: 41}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 53.4375},
			Land: 0.9429929256439209,
			Load: 0,
		},
		{Row: 3, Col: 42}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 59.0625},
			Land: 0.9755498170852661,
			Load: 0,
		},
		{Row: 3, Col: 43}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 64.6875},
			Land: 0.9718407988548279,
			Load: 0,
		},
		{Row: 3, Col: 44}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 70.3125},
			Land: 0.9089266657829285,
			Load: 0,
		},
		{Row: 3, Col: 45}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 75.9375},
			Land: 0.8974422812461853,
			Load: 0,
		},
		{Row: 3, Col: 46}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 81.5625},
			Land: 0.9823895692825317,
			Load: 0,
		},
		{Row: 3, Col: 47}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 87.1875},
			Land: 0.9692481160163879,
			Load: 0,
		},
		{Row: 3, Col: 48}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 92.8125},
			Land: 0.9809663891792297,
			Load: 0,
		},
		{Row: 3, Col: 49}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 98.4375},
			Land: 0.9909586310386658,
			Load: 0,
		},
		{Row: 3, Col: 50}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 104.0625},
			Land: 0.9879911541938782,
			Load: 0,
		},
		{Row: 3, Col: 51}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 109.6875},
			Land: 0.9864863157272339,
			Load: 0,
		},
		{Row: 3, Col: 52}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 115.3125},
			Land: 0.9848838448524475,
			Load: 0,
		},
		{Row: 3, Col: 53}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 120.9375},
			Land: 0.9723606705665588,
			Load: 0,
		},
		{Row: 3, Col: 54}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 126.5625},
			Land: 0.9678483605384827,
			Load: 0,
		},
		{Row: 3, Col: 55}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 132.1875},
			Land: 0.9858094453811646,
			Load: 0,
		},
		{Row: 3, Col: 56}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 137.8125},
			Land: 0.9933431148529053,
			Load: 0,
		},
		{Row: 3, Col: 57}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 143.4375},
			Land: 0.9794486165046692,
			Load: 0,
		},
		{Row: 3, Col: 58}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 149.0625},
			Land: 0.9745327830314636,
			Load: 0,
		},
		{Row: 3, Col: 59}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 154.6875},
			Land: 0.9672236442565918,
			Load: 0,
		},
		{Row: 3, Col: 60}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 160.3125},
			Land: 0.9830977916717529,
			Load: 0,
		},
		{Row: 3, Col: 61}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 165.9375},
			Land: 0.9932162165641785,
			Load: 0,
		},
		{Row: 3, Col: 62}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 171.5625},
			Land: 0.9875629544258118,
			Load: 0,
		},
		{Row: 3, Col: 63}: {
			S2:   dotworld.S2{Lat: 65.91796875, Long: 177.1875},
			Land: 0.8999456763267517,
			Load: 0,
		},
		{Row: 4, Col: 2}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -165.9375},
			Land: 0.2129896879196167,
			Load: 0,
		},
		{Row: 4, Col: 3}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -160.3125},
			Land: 0.699216365814209,
			Load: 0,
		},
		{Row: 4, Col: 4}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -154.6875},
			Land: 0.8094080090522766,
			Load: 0,
		},
		{Row: 4, Col: 5}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -149.0625},
			Land: 0.5066860914230347,
			Load: 0,
		},
		{Row: 4, Col: 6}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -143.4375},
			Land: 0.5203919410705566,
			Load: 0,
		},
		{Row: 4, Col: 7}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -137.8125},
			Land: 0.7496512532234192,
			Load: 0,
		},
		{Row: 4, Col: 8}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -132.1875},
			Land: 0.9638386964797974,
			Load: 0,
		},
		{Row: 4, Col: 9}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -126.5625},
			Land: 0.9885430932044983,
			Load: 0,
		},
		{Row: 4, Col: 10}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -120.9375},
			Land: 0.974480390548706,
			Load: 0,
		},
		{Row: 4, Col: 11}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -115.3125},
			Land: 0.857587993144989,
			Load: 0,
		},
		{Row: 4, Col: 12}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -109.6875},
			Land: 0.8690249919891357,
			Load: 0,
		},
		{Row: 4, Col: 13}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -104.0625},
			Land: 0.8520505428314209,
			Load: 0,
		},
		{Row: 4, Col: 14}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -98.4375},
			Land: 0.8844687938690186,
			Load: 0,
		},
		{Row: 4, Col: 15}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -92.8125},
			Land: 0.3289550542831421,
			Load: 0,
		},
		{Row: 4, Col: 18}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -75.9375},
			Land: 0.6693541407585144,
			Load: 0,
		},
		{Row: 4, Col: 19}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -70.3125},
			Land: 0.5689546465873718,
			Load: 0,
		},
		{Row: 4, Col: 20}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -64.6875},
			Land: 0.333041787147522,
			Load: 0,
		},
		{Row: 4, Col: 23}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -47.8125},
			Land: 0.327089786529541,
			Load: 0,
		},
		{Row: 4, Col: 24}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: -42.1875},
			Land: 0.2371419072151184,
			Load: 0,
		},
		{Row: 4, Col: 33}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 8.4375},
			Land: 0.7488616704940796,
			Load: 0,
		},
		{Row: 4, Col: 34}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 14.0625},
			Land: 0.9039078950881958,
			Load: 0,
		},
		{Row: 4, Col: 35}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 19.6875},
			Land: 0.279218852519989,
			Load: 0,
		},
		{Row: 4, Col: 36}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 25.3125},
			Land: 0.7297789454460144,
			Load: 0,
		},
		{Row: 4, Col: 37}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 30.9375},
			Land: 0.8324429392814636,
			Load: 0,
		},
		{Row: 4, Col: 38}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 36.5625},
			Land: 0.9021491408348083,
			Load: 0,
		},
		{Row: 4, Col: 39}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 42.1875},
			Land: 0.9873965978622437,
			Load: 0,
		},
		{Row: 4, Col: 40}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 47.8125},
			Land: 0.9870081543922424,
			Load: 0,
		},
		{Row: 4, Col: 41}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 53.4375},
			Land: 0.985370934009552,
			Load: 0,
		},
		{Row: 4, Col: 42}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 59.0625},
			Land: 0.9861641526222229,
			Load: 0,
		},
		{Row: 4, Col: 43}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 64.6875},
			Land: 0.9808914661407471,
			Load: 0,
		},
		{Row: 4, Col: 44}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 70.3125},
			Land: 0.9572344422340393,
			Load: 0,
		},
		{Row: 4, Col: 45}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 75.9375},
			Land: 0.976230263710022,
			Load: 0,
		},
		{Row: 4, Col: 46}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 81.5625},
			Land: 0.9825637936592102,
			Load: 0,
		},
		{Row: 4, Col: 47}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 87.1875},
			Land: 0.9903820753097534,
			Load: 0,
		},
		{Row: 4, Col: 48}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 92.8125},
			Land: 0.9869327545166016,
			Load: 0,
		},
		{Row: 4, Col: 49}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 98.4375},
			Land: 0.990190327167511,
			Load: 0,
		},
		{Row: 4, Col: 50}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 104.0625},
			Land: 0.9922023415565491,
			Load: 0,
		},
		{Row: 4, Col: 51}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 109.6875},
			Land: 0.9828656315803528,
			Load: 0,
		},
		{Row: 4, Col: 52}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 115.3125},
			Land: 0.9865796566009521,
			Load: 0,
		},
		{Row: 4, Col: 53}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 120.9375},
			Land: 0.9871857166290283,
			Load: 0,
		},
		{Row: 4, Col: 54}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 126.5625},
			Land: 0.9893568754196167,
			Load: 0,
		},
		{Row: 4, Col: 55}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 132.1875},
			Land: 0.9887551665306091,
			Load: 0,
		},
		{Row: 4, Col: 56}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 137.8125},
			Land: 0.981867790222168,
			Load: 0,
		},
		{Row: 4, Col: 57}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 143.4375},
			Land: 0.6978247165679932,
			Load: 0,
		},
		{Row: 4, Col: 58}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 149.0625},
			Land: 0.6411932110786438,
			Load: 0,
		},
		{Row: 4, Col: 59}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 154.6875},
			Land: 0.541784405708313,
			Load: 0,
		},
		{Row: 4, Col: 60}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 160.3125},
			Land: 0.5804857015609741,
			Load: 0,
		},
		{Row: 4, Col: 61}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 165.9375},
			Land: 0.4763391613960266,
			Load: 0,
		},
		{Row: 4, Col: 62}: {
			S2:   dotworld.S2{Lat: 60.29296875, Long: 171.5625},
			Land: 0.3924802541732788,
			Load: 0,
		},
		{Row: 5, Col: 8}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -132.1875},
			Land: 0.4297741651535034,
			Load: 0,
		},
		{Row: 5, Col: 9}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -126.5625},
			Land: 0.9442710876464844,
			Load: 0,
		},
		{Row: 5, Col: 10}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -120.9375},
			Land: 0.986955463886261,
			Load: 0,
		},
		{Row: 5, Col: 11}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -115.3125},
			Land: 0.9732024669647217,
			Load: 0,
		},
		{Row: 5, Col: 12}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -109.6875},
			Land: 0.9497178196907043,
			Load: 0,
		},
		{Row: 5, Col: 13}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -104.0625},
			Land: 0.9040498733520508,
			Load: 0,
		},
		{Row: 5, Col: 14}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -98.4375},
			Land: 0.804900050163269,
			Load: 0,
		},
		{Row: 5, Col: 15}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -92.8125},
			Land: 0.9150285124778748,
			Load: 0,
		},
		{Row: 5, Col: 16}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -87.1875},
			Land: 0.72723388671875,
			Load: 0,
		},
		{Row: 5, Col: 17}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -81.5625},
			Land: 0.3064934015274048,
			Load: 0,
		},
		{Row: 5, Col: 18}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -75.9375},
			Land: 0.7692399621009827,
			Load: 0,
		},
		{Row: 5, Col: 19}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -70.3125},
			Land: 0.9197155237197876,
			Load: 0,
		},
		{Row: 5, Col: 20}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -64.6875},
			Land: 0.9077723026275635,
			Load: 0,
		},
		{Row: 5, Col: 21}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -59.0625},
			Land: 0.5487421751022339,
			Load: 0,
		},
		{Row: 5, Col: 30}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -8.4375},
			Land: 0.3733695149421692,
			Load: 0,
		},
		{Row: 5, Col: 31}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: -2.8125},
			Land: 0.6181025505065918,
			Load: 0,
		},
		{Row: 5, Col: 33}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 8.4375},
			Land: 0.5408004522323608,
			Load: 0,
		},
		{Row: 5, Col: 34}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 14.0625},
			Land: 0.6540850400924683,
			Load: 0,
		},
		{Row: 5, Col: 35}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 19.6875},
			Land: 0.6226754188537598,
			Load: 0,
		},
		{Row: 5, Col: 36}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 25.3125},
			Land: 0.9702224731445312,
			Load: 0,
		},
		{Row: 5, Col: 37}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 30.9375},
			Land: 0.9834800362586975,
			Load: 0,
		},
		{Row: 5, Col: 38}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 36.5625},
			Land: 0.9857029318809509,
			Load: 0,
		},
		{Row: 5, Col: 39}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 42.1875},
			Land: 0.9861495494842529,
			Load: 0,
		},
		{Row: 5, Col: 40}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 47.8125},
			Land: 0.9622003436088562,
			Load: 0,
		},
		{Row: 5, Col: 41}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 53.4375},
			Land: 0.9872292876243591,
			Load: 0,
		},
		{Row: 5, Col: 42}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 59.0625},
			Land: 0.9874492287635803,
			Load: 0,
		},
		{Row: 5, Col: 43}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 64.6875},
			Land: 0.9807961583137512,
			Load: 0,
		},
		{Row: 5, Col: 44}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 70.3125},
			Land: 0.9834185242652893,
			Load: 0,
		},
		{Row: 5, Col: 45}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 75.9375},
			Land: 0.9698883891105652,
			Load: 0,
		},
		{Row: 5, Col: 46}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 81.5625},
			Land: 0.9828553199768066,
			Load: 0,
		},
		{Row: 5, Col: 47}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 87.1875},
			Land: 0.9912410974502563,
			Load: 0,
		},
		{Row: 5, Col: 48}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 92.8125},
			Land: 0.979071855545044,
			Load: 0,
		},
		{Row: 5, Col: 49}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 98.4375},
			Land: 0.9904974102973938,
			Load: 0,
		},
		{Row: 5, Col: 50}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 104.0625},
			Land: 0.9470252990722656,
			Load: 0,
		},
		{Row: 5, Col: 51}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 109.6875},
			Land: 0.8997297883033752,
			Load: 0,
		},
		{Row: 5, Col: 52}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 115.3125},
			Land: 0.9908684492111206,
			Load: 0,
		},
		{Row: 5, Col: 53}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 120.9375},
			Land: 0.9895328283309937,
			Load: 0,
		},
		{Row: 5, Col: 54}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 126.5625},
			Land: 0.9859015941619873,
			Load: 0,
		},
		{Row: 5, Col: 55}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 132.1875},
			Land: 0.9917784333229065,
			Load: 0,
		},
		{Row: 5, Col: 56}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 137.8125},
			Land: 0.6227335929870605,
			Load: 0,
		},
		{Row: 5, Col: 59}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 154.6875},
			Land: 0.2655874490737915,
			Load: 0,
		},
		{Row: 5, Col: 60}: {
			S2:   dotworld.S2{Lat: 54.66796875, Long: 160.3125},
			Land: 0.5950645208358765,
			Load: 0,
		},
		{Row: 6, Col: 9}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -126.5625},
			Land: 0.3475602865219116,
			Load: 0,
		},
		{Row: 6, Col: 10}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -120.9375},
			Land: 0.9474109411239624,
			Load: 0,
		},
		{Row: 6, Col: 11}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -115.3125},
			Land: 0.9803096055984497,
			Load: 0,
		},
		{Row: 6, Col: 12}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -109.6875},
			Land: 0.9889464378356934,
			Load: 0,
		},
		{Row: 6, Col: 13}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -104.0625},
			Land: 0.9842404723167419,
			Load: 0,
		},
		{Row: 6, Col: 14}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -98.4375},
			Land: 0.9435365200042725,
			Load: 0,
		},
		{Row: 6, Col: 15}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -92.8125},
			Land: 0.8595786690711975,
			Load: 0,
		},
		{Row: 6, Col: 16}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -87.1875},
			Land: 0.6965032815933228,
			Load: 0,
		},
		{Row: 6, Col: 17}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -81.5625},
			Land: 0.9421578049659729,
			Load: 0,
		},
		{Row: 6, Col: 18}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -75.9375},
			Land: 0.9314077496528625,
			Load: 0,
		},
		{Row: 6, Col: 19}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -70.3125},
			Land: 0.9086442589759827,
			Load: 0,
		},
		{Row: 6, Col: 20}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -64.6875},
			Land: 0.5839608907699585,
			Load: 0,
		},
		{Row: 6, Col: 21}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -59.0625},
			Land: 0.3936583399772644,
			Load: 0,
		},
		{Row: 6, Col: 22}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -53.4375},
			Land: 0.22176319360733032,
			Load: 0,
		},
		{Row: 6, Col: 31}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: -2.8125},
			Land: 0.44841259717941284,
			Load: 0,
		},
		{Row: 6, Col: 32}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 2.8125},
			Land: 0.8779423832893372,
			Load: 0,
		},
		{Row: 6, Col: 33}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 8.4375},
			Land: 0.9782968759536743,
			Load: 0,
		},
		{Row: 6, Col: 34}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 14.0625},
			Land: 0.9863865375518799,
			Load: 0,
		},
		{Row: 6, Col: 35}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 19.6875},
			Land: 0.9857491254806519,
			Load: 0,
		},
		{Row: 6, Col: 36}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 25.3125},
			Land: 0.9908564686775208,
			Load: 0,
		},
		{Row: 6, Col: 37}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 30.9375},
			Land: 0.9565180540084839,
			Load: 0,
		},
		{Row: 6, Col: 38}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 36.5625},
			Land: 0.9201222062110901,
			Load: 0,
		},
		{Row: 6, Col: 39}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 42.1875},
			Land: 0.9749197959899902,
			Load: 0,
		},
		{Row: 6, Col: 40}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 47.8125},
			Land: 0.9655148983001709,
			Load: 0,
		},
		{Row: 6, Col: 41}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 53.4375},
			Land: 0.9425163865089417,
			Load: 0,
		},
		{Row: 6, Col: 42}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 59.0625},
			Land: 0.9832189083099365,
			Load: 0,
		},
		{Row: 6, Col: 43}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 64.6875},
			Land: 0.9941451549530029,
			Load: 0,
		},
		{Row: 6, Col: 44}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 70.3125},
			Land: 0.9941482543945312,
			Load: 0,
		},
		{Row: 6, Col: 45}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 75.9375},
			Land: 0.9591241478919983,
			Load: 0,
		},
		{Row: 6, Col: 46}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 81.5625},
			Land: 0.9703450798988342,
			Load: 0,
		},
		{Row: 6, Col: 47}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 87.1875},
			Land: 0.9850418567657471,
			Load: 0,
		},
		{Row: 6, Col: 48}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 92.8125},
			Land: 0.9652085304260254,
			Load: 0,
		},
		{Row: 6, Col: 49}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 98.4375},
			Land: 0.9819668531417847,
			Load: 0,
		},
		{Row: 6, Col: 50}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 104.0625},
			Land: 0.9763583540916443,
			Load: 0,
		},
		{Row: 6, Col: 51}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 109.6875},
			Land: 0.9946793913841248,
			Load: 0,
		},
		{Row: 6, Col: 52}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 115.3125},
			Land: 0.9782356023788452,
			Load: 0,
		},
		{Row: 6, Col: 53}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 120.9375},
			Land: 0.9931061267852783,
			Load: 0,
		},
		{Row: 6, Col: 54}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 126.5625},
			Land: 0.9864016175270081,
			Load: 0,
		},
		{Row: 6, Col: 55}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 132.1875},
			Land: 0.9865390062332153,
			Load: 0,
		},
		{Row: 6, Col: 56}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 137.8125},
			Land: 0.8466078639030457,
			Load: 0,
		},
		{Row: 6, Col: 57}: {
			S2:   dotworld.S2{Lat: 49.04296875, Long: 143.4375},
			Land: 0.21954107284545898,
			Load: 0,
		},
		{Row: 7, Col: 10}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -120.9375},
			Land: 0.9806846380233765,
			Load: 0,
		},
		{Row: 7, Col: 11}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -115.3125},
			Land: 0.9804793000221252,
			Load: 0,
		},
		{Row: 7, Col: 12}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -109.6875},
			Land: 0.9778188467025757,
			Load: 0,
		},
		{Row: 7, Col: 13}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -104.0625},
			Land: 0.9924773573875427,
			Load: 0,
		},
		{Row: 7, Col: 14}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -98.4375},
			Land: 0.9804218411445618,
			Load: 0,
		},
		{Row: 7, Col: 15}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -92.8125},
			Land: 0.9803897738456726,
			Load: 0,
		},
		{Row: 7, Col: 16}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -87.1875},
			Land: 0.7800800204277039,
			Load: 0,
		},
		{Row: 7, Col: 17}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -81.5625},
			Land: 0.6778640747070312,
			Load: 0,
		},
		{Row: 7, Col: 18}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -75.9375},
			Land: 0.9133834838867188,
			Load: 0,
		},
		{Row: 7, Col: 19}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -70.3125},
			Land: 0.5834929943084717,
			Load: 0,
		},
		{Row: 7, Col: 20}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -64.6875},
			Land: 0.2507757544517517,
			Load: 0,
		},
		{Row: 7, Col: 30}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -8.4375},
			Land: 0.30567461252212524,
			Load: 0,
		},
		{Row: 7, Col: 31}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: -2.8125},
			Land: 0.6106385588645935,
			Load: 0,
		},
		{Row: 7, Col: 32}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 2.8125},
			Land: 0.7129339575767517,
			Load: 0,
		},
		{Row: 7, Col: 33}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 8.4375},
			Land: 0.5010428428649902,
			Load: 0,
		},
		{Row: 7, Col: 34}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 14.0625},
			Land: 0.6038267612457275,
			Load: 0,
		},
		{Row: 7, Col: 35}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 19.6875},
			Land: 0.8322935700416565,
			Load: 0,
		},
		{Row: 7, Col: 36}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 25.3125},
			Land: 0.9410108327865601,
			Load: 0,
		},
		{Row: 7, Col: 37}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 30.9375},
			Land: 0.26191145181655884,
			Load: 0,
		},
		{Row: 7, Col: 38}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 36.5625},
			Land: 0.3292995095252991,
			Load: 0,
		},
		{Row: 7, Col: 39}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 42.1875},
			Land: 0.8466916680335999,
			Load: 0,
		},
		{Row: 7, Col: 40}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 47.8125},
			Land: 0.5348159074783325,
			Load: 0,
		},
		{Row: 7, Col: 41}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 53.4375},
			Land: 0.69755619764328,
			Load: 0,
		},
		{Row: 7, Col: 42}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 59.0625},
			Land: 0.9036044478416443,
			Load: 0,
		},
		{Row: 7, Col: 43}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 64.6875},
			Land: 0.9949336051940918,
			Load: 0,
		},
		{Row: 7, Col: 44}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 70.3125},
			Land: 0.9915769100189209,
			Load: 0,
		},
		{Row: 7, Col: 45}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 75.9375},
			Land: 0.945285439491272,
			Load: 0,
		},
		{Row: 7, Col: 46}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 81.5625},
			Land: 0.9841808676719666,
			Load: 0,
		},
		{Row: 7, Col: 47}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 87.1875},
			Land: 0.9908720254898071,
			Load: 0,
		},
		{Row: 7, Col: 48}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 92.8125},
			Land: 0.9996818900108337,
			Load: 0,
		},
		{Row: 7, Col: 49}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 98.4375},
			Land: 0.997829794883728,
			Load: 0,
		},
		{Row: 7, Col: 50}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 104.0625},
			Land: 0.999667763710022,
			Load: 0,
		},
		{Row: 7, Col: 51}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 109.6875},
			Land: 0.9944649338722229,
			Load: 0,
		},
		{Row: 7, Col: 52}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 115.3125},
			Land: 0.9950621128082275,
			Load: 0,
		},
		{Row: 7, Col: 53}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 120.9375},
			Land: 0.980414628982544,
			Load: 0,
		},
		{Row: 7, Col: 54}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 126.5625},
			Land: 0.9840008616447449,
			Load: 0,
		},
		{Row: 7, Col: 55}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 132.1875},
			Land: 0.6089862585067749,
			Load: 0,
		},
		{Row: 7, Col: 57}: {
			S2:   dotworld.S2{Lat: 43.41796875, Long: 143.4375},
			Land: 0.27084434032440186,
			Load: 0,
		},
		{Row: 8, Col: 10}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -120.9375},
			Land: 0.7796063423156738,
			Load: 0,
		},
		{Row: 8, Col: 11}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -115.3125},
			Land: 0.9953410029411316,
			Load: 0,
		},
		{Row: 8, Col: 12}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -109.6875},
			Land: 0.987524151802063,
			Load: 0,
		},
		{Row: 8, Col: 13}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -104.0625},
			Land: 0.9900400042533875,
			Load: 0,
		},
		{Row: 8, Col: 14}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -98.4375},
			Land: 0.988556981086731,
			Load: 0,
		},
		{Row: 8, Col: 15}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -92.8125},
			Land: 0.9736282825469971,
			Load: 0,
		},
		{Row: 8, Col: 16}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -87.1875},
			Land: 0.9748702645301819,
			Load: 0,
		},
		{Row: 8, Col: 17}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -81.5625},
			Land: 0.9830511212348938,
			Load: 0,
		},
		{Row: 8, Col: 18}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -75.9375},
			Land: 0.5619159936904907,
			Load: 0,
		},
		{Row: 8, Col: 30}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -8.4375},
			Land: 0.39987003803253174,
			Load: 0,
		},
		{Row: 8, Col: 31}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: -2.8125},
			Land: 0.6916700601577759,
			Load: 0,
		},
		{Row: 8, Col: 32}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 2.8125},
			Land: 0.3243151903152466,
			Load: 0,
		},
		{Row: 8, Col: 33}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 8.4375},
			Land: 0.39946597814559937,
			Load: 0,
		},
		{Row: 8, Col: 35}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 19.6875},
			Land: 0.23095011711120605,
			Load: 0,
		},
		{Row: 8, Col: 36}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 25.3125},
			Land: 0.3131098747253418,
			Load: 0,
		},
		{Row: 8, Col: 37}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 30.9375},
			Land: 0.7311071157455444,
			Load: 0,
		},
		{Row: 8, Col: 38}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 36.5625},
			Land: 0.8804512619972229,
			Load: 0,
		},
		{Row: 8, Col: 39}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 42.1875},
			Land: 0.9777683615684509,
			Load: 0,
		},
		{Row: 8, Col: 40}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 47.8125},
			Land: 0.832836925983429,
			Load: 0,
		},
		{Row: 8, Col: 41}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 53.4375},
			Land: 0.640669047832489,
			Load: 0,
		},
		{Row: 8, Col: 42}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 59.0625},
			Land: 0.9972292184829712,
			Load: 0,
		},
		{Row: 8, Col: 43}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 64.6875},
			Land: 0.9915094375610352,
			Load: 0,
		},
		{Row: 8, Col: 44}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 70.3125},
			Land: 0.9906989336013794,
			Load: 0,
		},
		{Row: 8, Col: 45}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 75.9375},
			Land: 0.9913933277130127,
			Load: 0,
		},
		{Row: 8, Col: 46}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 81.5625},
			Land: 0.9939348101615906,
			Load: 0,
		},
		{Row: 8, Col: 47}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 87.1875},
			Land: 0.9911178350448608,
			Load: 0,
		},
		{Row: 8, Col: 48}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 92.8125},
			Land: 0.9899365901947021,
			Load: 0,
		},
		{Row: 8, Col: 49}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 98.4375},
			Land: 0.9782726764678955,
			Load: 0,
		},
		{Row: 8, Col: 50}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 104.0625},
			Land: 0.9931506514549255,
			Load: 0,
		},
		{Row: 8, Col: 51}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 109.6875},
			Land: 0.9854276776313782,
			Load: 0,
		},
		{Row: 8, Col: 52}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 115.3125},
			Land: 0.9737955927848816,
			Load: 0,
		},
		{Row: 8, Col: 53}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 120.9375},
			Land: 0.3725370764732361,
			Load: 0,
		},
		{Row: 8, Col: 54}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 126.5625},
			Land: 0.548625111579895,
			Load: 0,
		},
		{Row: 8, Col: 56}: {
			S2:   dotworld.S2{Lat: 37.79296875, Long: 137.8125},
			Land: 0.4219204783439636,
			Load: 0,
		},
		{Row: 9, Col: 11}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -115.3125},
			Land: 0.6620995998382568,
			Load: 0,
		},
		{Row: 9, Col: 12}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -109.6875},
			Land: 0.9939537048339844,
			Load: 0,
		},
		{Row: 9, Col: 13}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -104.0625},
			Land: 0.9900861978530884,
			Load: 0,
		},
		{Row: 9, Col: 14}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -98.4375},
			Land: 0.984155535697937,
			Load: 0,
		},
		{Row: 9, Col: 15}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -92.8125},
			Land: 0.925122082233429,
			Load: 0,
		},
		{Row: 9, Col: 16}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -87.1875},
			Land: 0.8352184891700745,
			Load: 0,
		},
		{Row: 9, Col: 17}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -81.5625},
			Land: 0.6961081027984619,
			Load: 0,
		},
		{Row: 9, Col: 30}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -8.4375},
			Land: 0.5638836622238159,
			Load: 0,
		},
		{Row: 9, Col: 31}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: -2.8125},
			Land: 0.9987335801124573,
			Load: 0,
		},
		{Row: 9, Col: 32}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 2.8125},
			Land: 0.9999784827232361,
			Load: 0,
		},
		{Row: 9, Col: 33}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 8.4375},
			Land: 0.9636154174804688,
			Load: 0,
		},
		{Row: 9, Col: 34}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 14.0625},
			Land: 0.54608154296875,
			Load: 0,
		},
		{Row: 9, Col: 35}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 19.6875},
			Land: 0.4007120728492737,
			Load: 0,
		},
		{Row: 9, Col: 36}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 25.3125},
			Land: 0.4407367706298828,
			Load: 0,
		},
		{Row: 9, Col: 37}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 30.9375},
			Land: 0.3325434923171997,
			Load: 0,
		},
		{Row: 9, Col: 38}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 36.5625},
			Land: 0.8306659460067749,
			Load: 0,
		},
		{Row: 9, Col: 39}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 42.1875},
			Land: 0.9814872145652771,
			Load: 0,
		},
		{Row: 9, Col: 40}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 47.8125},
			Land: 0.9301295876502991,
			Load: 0,
		},
		{Row: 9, Col: 41}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 53.4375},
			Land: 0.9996210932731628,
			Load: 0,
		},
		{Row: 9, Col: 42}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 59.0625},
			Land: 0.9957675337791443,
			Load: 0,
		},
		{Row: 9, Col: 43}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 64.6875},
			Land: 0.9943026900291443,
			Load: 0,
		},
		{Row: 9, Col: 44}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 70.3125},
			Land: 0.9878436923027039,
			Load: 0,
		},
		{Row: 9, Col: 45}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 75.9375},
			Land: 0.9842960238456726,
			Load: 0,
		},
		{Row: 9, Col: 46}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 81.5625},
			Land: 0.9781925082206726,
			Load: 0,
		},
		{Row: 9, Col: 47}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 87.1875},
			Land: 0.9663026332855225,
			Load: 0,
		},
		{Row: 9, Col: 48}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 92.8125},
			Land: 0.9809297323226929,
			Load: 0,
		},
		{Row: 9, Col: 49}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 98.4375},
			Land: 0.9815803170204163,
			Load: 0,
		},
		{Row: 9, Col: 50}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 104.0625},
			Land: 0.9900088906288147,
			Load: 0,
		},
		{Row: 9, Col: 51}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 109.6875},
			Land: 0.9804603457450867,
			Load: 0,
		},
		{Row: 9, Col: 52}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 115.3125},
			Land: 0.9641352891921997,
			Load: 0,
		},
		{Row: 9, Col: 53}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 120.9375},
			Land: 0.4961373209953308,
			Load: 0,
		},
		{Row: 9, Col: 55}: {
			S2:   dotworld.S2{Lat: 32.16796875, Long: 132.1875},
			Land: 0.25660115480422974,
			Load: 0,
		},
		{Row: 10, Col: 12}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -109.6875},
			Land: 0.6103883981704712,
			Load: 0,
		},
		{Row: 10, Col: 13}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -104.0625},
			Land: 0.9961236715316772,
			Load: 0,
		},
		{Row: 10, Col: 14}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -98.4375},
			Land: 0.7160400152206421,
			Load: 0,
		},
		{Row: 10, Col: 17}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -81.5625},
			Land: 0.23918622732162476,
			Load: 0,
		},
		{Row: 10, Col: 29}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -14.0625},
			Land: 0.45329612493515015,
			Load: 0,
		},
		{Row: 10, Col: 30}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -8.4375},
			Land: 0.9873108863830566,
			Load: 0,
		},
		{Row: 10, Col: 31}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: -2.8125},
			Land: 0.9999918341636658,
			Load: 0,
		},
		{Row: 10, Col: 32}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 2.8125},
			Land: 0.9999949932098389,
			Load: 0,
		},
		{Row: 10, Col: 33}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 8.4375},
			Land: 1,
			Load: 0,
		},
		{Row: 10, Col: 34}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 14.0625},
			Land: 1,
			Load: 0,
		},
		{Row: 10, Col: 35}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 19.6875},
			Land: 1,
			Load: 0,
		},
		{Row: 10, Col: 36}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 25.3125},
			Land: 0.9998128414154053,
			Load: 0,
		},
		{Row: 10, Col: 37}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 30.9375},
			Land: 0.9722050428390503,
			Load: 0,
		},
		{Row: 10, Col: 38}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 36.5625},
			Land: 0.6981524229049683,
			Load: 0,
		},
		{Row: 10, Col: 39}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 42.1875},
			Land: 1,
			Load: 0,
		},
		{Row: 10, Col: 40}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 47.8125},
			Land: 0.8344113826751709,
			Load: 0,
		},
		{Row: 10, Col: 41}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 53.4375},
			Land: 0.5583555698394775,
			Load: 0,
		},
		{Row: 10, Col: 42}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 59.0625},
			Land: 0.6751003265380859,
			Load: 0,
		},
		{Row: 10, Col: 43}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 64.6875},
			Land: 0.7313534021377563,
			Load: 0,
		},
		{Row: 10, Col: 44}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 70.3125},
			Land: 0.9863185286521912,
			Load: 0,
		},
		{Row: 10, Col: 45}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 75.9375},
			Land: 0.9884985685348511,
			Load: 0,
		},
		{Row: 10, Col: 46}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 81.5625},
			Land: 0.9769284725189209,
			Load: 0,
		},
		{Row: 10, Col: 47}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 87.1875},
			Land: 0.9745466709136963,
			Load: 0,
		},
		{Row: 10, Col: 48}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 92.8125},
			Land: 0.9754631519317627,
			Load: 0,
		},
		{Row: 10, Col: 49}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 98.4375},
			Land: 0.9764648675918579,
			Load: 0,
		},
		{Row: 10, Col: 50}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 104.0625},
			Land: 0.9810932278633118,
			Load: 0,
		},
		{Row: 10, Col: 51}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 109.6875},
			Land: 0.9887144565582275,
			Load: 0,
		},
		{Row: 10, Col: 52}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 115.3125},
			Land: 0.977311909198761,
			Load: 0,
		},
		{Row: 10, Col: 53}: {
			S2:   dotworld.S2{Lat: 26.54296875, Long: 120.9375},
			Land: 0.3776058554649353,
			Load: 0,
		},
		{Row: 11, Col: 13}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -104.0625},
			Land: 0.7050901055335999,
			Load: 0,
		},
		{Row: 11, Col: 14}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -98.4375},
			Land: 0.7462603449821472,
			Load: 0,
		},
		{Row: 11, Col: 16}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -87.1875},
			Land: 0.2755972146987915,
			Load: 0,
		},
		{Row: 11, Col: 18}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -75.9375},
			Land: 0.20419609546661377,
			Load: 0,
		},
		{Row: 11, Col: 29}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -14.0625},
			Land: 0.9194328784942627,
			Load: 0,
		},
		{Row: 11, Col: 30}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -8.4375},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 31}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: -2.8125},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 32}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 2.8125},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 33}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 8.4375},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 34}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 14.0625},
			Land: 0.9999911189079285,
			Load: 0,
		},
		{Row: 11, Col: 35}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 19.6875},
			Land: 0.9999526143074036,
			Load: 0,
		},
		{Row: 11, Col: 36}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 25.3125},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 37}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 30.9375},
			Land: 0.9840935468673706,
			Load: 0,
		},
		{Row: 11, Col: 38}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 36.5625},
			Land: 0.6023696064949036,
			Load: 0,
		},
		{Row: 11, Col: 39}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 42.1875},
			Land: 0.8838759660720825,
			Load: 0,
		},
		{Row: 11, Col: 40}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 47.8125},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 41}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 53.4375},
			Land: 1,
			Load: 0,
		},
		{Row: 11, Col: 42}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 59.0625},
			Land: 0.38793277740478516,
			Load: 0,
		},
		{Row: 11, Col: 44}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 70.3125},
			Land: 0.3404545783996582,
			Load: 0,
		},
		{Row: 11, Col: 45}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 75.9375},
			Land: 0.9874222278594971,
			Load: 0,
		},
		{Row: 11, Col: 46}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 81.5625},
			Land: 0.9829175472259521,
			Load: 0,
		},
		{Row: 11, Col: 47}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 87.1875},
			Land: 0.5046829581260681,
			Load: 0,
		},
		{Row: 11, Col: 48}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 92.8125},
			Land: 0.590795636177063,
			Load: 0,
		},
		{Row: 11, Col: 49}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 98.4375},
			Land: 0.9824192523956299,
			Load: 0,
		},
		{Row: 11, Col: 50}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 104.0625},
			Land: 0.9154316186904907,
			Load: 0,
		},
		{Row: 11, Col: 51}: {
			S2:   dotworld.S2{Lat: 20.91796875, Long: 109.6875},
			Land: 0.5125873684883118,
			Load: 0,
		},
		{Row: 12, Col: 14}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: -98.4375},
			Land: 0.3045295476913452,
			Load: 0,
		},
		{Row: 12, Col: 15}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: -92.8125},
			Land: 0.5291522741317749,
			Load: 0,
		},
		{Row: 12, Col: 16}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: -87.1875},
			Land: 0.6397966146469116,
			Load: 0,
		},
		{Row: 12, Col: 29}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: -14.0625},
			Land: 0.9365485906600952,
			Load: 0,
		},
		{Row: 12, Col: 30}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: -8.4375},
			Land: 0.9961179494857788,
			Load: 0,
		},
		{Row: 12, Col: 31}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: -2.8125},
			Land: 0.9855248332023621,
			Load: 0,
		},
		{Row: 12, Col: 32}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 2.8125},
			Land: 0.9962684512138367,
			Load: 0,
		},
		{Row: 12, Col: 33}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 8.4375},
			Land: 0.9996500611305237,
			Load: 0,
		},
		{Row: 12, Col: 34}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 14.0625},
			Land: 0.9958720803260803,
			Load: 0,
		},
		{Row: 12, Col: 35}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 19.6875},
			Land: 0.9996220469474792,
			Load: 0,
		},
		{Row: 12, Col: 36}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 25.3125},
			Land: 0.9999969005584717,
			Load: 0,
		},
		{Row: 12, Col: 37}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 30.9375},
			Land: 0.9921314716339111,
			Load: 0,
		},
		{Row: 12, Col: 38}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 36.5625},
			Land: 0.9699249863624573,
			Load: 0,
		},
		{Row: 12, Col: 39}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 42.1875},
			Land: 0.6046525239944458,
			Load: 0,
		},
		{Row: 12, Col: 40}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 47.8125},
			Land: 0.7332000136375427,
			Load: 0,
		},
		{Row: 12, Col: 41}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 53.4375},
			Land: 0.2762613892555237,
			Load: 0,
		},
		{Row: 12, Col: 45}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 75.9375},
			Land: 0.8403483033180237,
			Load: 0,
		},
		{Row: 12, Col: 46}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 81.5625},
			Land: 0.40354984998703003,
			Load: 0,
		},
		{Row: 12, Col: 49}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 98.4375},
			Land: 0.6438004970550537,
			Load: 0,
		},
		{Row: 12, Col: 50}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 104.0625},
			Land: 0.9619298577308655,
			Load: 0,
		},
		{Row: 12, Col: 51}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 109.6875},
			Land: 0.27195996046066284,
			Load: 0,
		},
		{Row: 12, Col: 53}: {
			S2:   dotworld.S2{Lat: 15.29296875, Long: 120.9375},
			Land: 0.28844255208969116,
			Load: 0,
		},
		{Row: 13, Col: 17}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -81.5625},
			Land: 0.24981260299682617,
			Load: 0,
		},
		{Row: 13, Col: 18}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -75.9375},
			Land: 0.49693888425827026,
			Load: 0,
		},
		{Row: 13, Col: 19}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -70.3125},
			Land: 0.7764713168144226,
			Load: 0,
		},
		{Row: 13, Col: 20}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -64.6875},
			Land: 0.6270493268966675,
			Load: 0,
		},
		{Row: 13, Col: 21}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -59.0625},
			Land: 0.21135807037353516,
			Load: 0,
		},
		{Row: 13, Col: 29}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -14.0625},
			Land: 0.4907240867614746,
			Load: 0,
		},
		{Row: 13, Col: 30}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -8.4375},
			Land: 0.9905783534049988,
			Load: 0,
		},
		{Row: 13, Col: 31}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: -2.8125},
			Land: 0.9817332625389099,
			Load: 0,
		},
		{Row: 13, Col: 32}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 2.8125},
			Land: 0.9824254512786865,
			Load: 0,
		},
		{Row: 13, Col: 33}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 8.4375},
			Land: 0.9904507398605347,
			Load: 0,
		},
		{Row: 13, Col: 34}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 14.0625},
			Land: 0.992363691329956,
			Load: 0,
		},
		{Row: 13, Col: 35}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 19.6875},
			Land: 0.9937852025032043,
			Load: 0,
		},
		{Row: 13, Col: 36}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 25.3125},
			Land: 0.9987773895263672,
			Load: 0,
		},
		{Row: 13, Col: 37}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 30.9375},
			Land: 0.9901999235153198,
			Load: 0,
		},
		{Row: 13, Col: 38}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 36.5625},
			Land: 0.9796326756477356,
			Load: 0,
		},
		{Row: 13, Col: 39}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 42.1875},
			Land: 0.8986198902130127,
			Load: 0,
		},
		{Row: 13, Col: 40}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 47.8125},
			Land: 0.7132740616798401,
			Load: 0,
		},
		{Row: 13, Col: 45}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 75.9375},
			Land: 0.3409414291381836,
			Load: 0,
		},
		{Row: 13, Col: 46}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 81.5625},
			Land: 0.2152460813522339,
			Load: 0,
		},
		{Row: 13, Col: 49}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 98.4375},
			Land: 0.21349257230758667,
			Load: 0,
		},
		{Row: 13, Col: 50}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 104.0625},
			Land: 0.3149791955947876,
			Load: 0,
		},
		{Row: 13, Col: 54}: {
			S2:   dotworld.S2{Lat: 9.66796875, Long: 126.5625},
			Land: 0.23899096250534058,
			Load: 0,
		},
		{Row: 14, Col: 18}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -75.9375},
			Land: 0.8107582330703735,
			Load: 0,
		},
		{Row: 14, Col: 19}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -70.3125},
			Land: 0.9866177439689636,
			Load: 0,
		},
		{Row: 14, Col: 20}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -64.6875},
			Land: 0.9901702404022217,
			Load: 0,
		},
		{Row: 14, Col: 21}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -59.0625},
			Land: 0.9445001482963562,
			Load: 0,
		},
		{Row: 14, Col: 22}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -53.4375},
			Land: 0.6981036067008972,
			Load: 0,
		},
		{Row: 14, Col: 30}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -8.4375},
			Land: 0.2929694652557373,
			Load: 0,
		},
		{Row: 14, Col: 31}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: -2.8125},
			Land: 0.2921144962310791,
			Load: 0,
		},
		{Row: 14, Col: 33}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 8.4375},
			Land: 0.5851632356643677,
			Load: 0,
		},
		{Row: 14, Col: 34}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 14.0625},
			Land: 0.987736701965332,
			Load: 0,
		},
		{Row: 14, Col: 35}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 19.6875},
			Land: 0.9861002564430237,
			Load: 0,
		},
		{Row: 14, Col: 36}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 25.3125},
			Land: 0.9883930087089539,
			Load: 0,
		},
		{Row: 14, Col: 37}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 30.9375},
			Land: 0.9753384590148926,
			Load: 0,
		},
		{Row: 14, Col: 38}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 36.5625},
			Land: 0.9729678630828857,
			Load: 0,
		},
		{Row: 14, Col: 39}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 42.1875},
			Land: 0.9843278527259827,
			Load: 0,
		},
		{Row: 14, Col: 40}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 47.8125},
			Land: 0.4106450080871582,
			Load: 0,
		},
		{Row: 14, Col: 49}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 98.4375},
			Land: 0.40475547313690186,
			Load: 0,
		},
		{Row: 14, Col: 50}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 104.0625},
			Land: 0.3147432208061218,
			Load: 0,
		},
		{Row: 14, Col: 52}: {
			S2:   dotworld.S2{Lat: 4.04296875, Long: 115.3125},
			Land: 0.6711351871490479,
			Load: 0,
		},
		{Row: 15, Col: 17}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -81.5625},
			Land: 0.29905837774276733,
			Load: 0,
		},
		{Row: 15, Col: 18}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -75.9375},
			Land: 0.9871823787689209,
			Load: 0,
		},
		{Row: 15, Col: 19}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -70.3125},
			Land: 0.9780963063240051,
			Load: 0,
		},
		{Row: 15, Col: 20}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -64.6875},
			Land: 0.9592570066452026,
			Load: 0,
		},
		{Row: 15, Col: 21}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -59.0625},
			Land: 0.9545950889587402,
			Load: 0,
		},
		{Row: 15, Col: 22}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -53.4375},
			Land: 0.9483336210250854,
			Load: 0,
		},
		{Row: 15, Col: 23}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -47.8125},
			Land: 0.6670252084732056,
			Load: 0,
		},
		{Row: 15, Col: 24}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: -42.1875},
			Land: 0.31495314836502075,
			Load: 0,
		},
		{Row: 15, Col: 33}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 8.4375},
			Land: 0.25987333059310913,
			Load: 0,
		},
		{Row: 15, Col: 34}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 14.0625},
			Land: 0.9860119223594666,
			Load: 0,
		},
		{Row: 15, Col: 35}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 19.6875},
			Land: 0.9733850955963135,
			Load: 0,
		},
		{Row: 15, Col: 36}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 25.3125},
			Land: 0.9886792898178101,
			Load: 0,
		},
		{Row: 15, Col: 37}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 30.9375},
			Land: 0.822380781173706,
			Load: 0,
		},
		{Row: 15, Col: 38}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 36.5625},
			Land: 0.9721210598945618,
			Load: 0,
		},
		{Row: 15, Col: 39}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 42.1875},
			Land: 0.3812614679336548,
			Load: 0,
		},
		{Row: 15, Col: 50}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 104.0625},
			Land: 0.5916496515274048,
			Load: 0,
		},
		{Row: 15, Col: 51}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 109.6875},
			Land: 0.4105203151702881,
			Load: 0,
		},
		{Row: 15, Col: 52}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 115.3125},
			Land: 0.6745522022247314,
			Load: 0,
		},
		{Row: 15, Col: 53}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 120.9375},
			Land: 0.3910776376724243,
			Load: 0,
		},
		{Row: 15, Col: 55}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 132.1875},
			Land: 0.2906225919723511,
			Load: 0,
		},
		{Row: 15, Col: 56}: {
			S2:   dotworld.S2{Lat: -1.58203125, Long: 137.8125},
			Land: 0.3964415192604065,
			Load: 0,
		},
		{Row: 16, Col: 18}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -75.9375},
			Land: 0.971757709980011,
			Load: 0,
		},
		{Row: 16, Col: 19}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -70.3125},
			Land: 0.9923859238624573,
			Load: 0,
		},
		{Row: 16, Col: 20}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -64.6875},
			Land: 0.9801573753356934,
			Load: 0,
		},
		{Row: 16, Col: 21}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -59.0625},
			Land: 0.9839999079704285,
			Load: 0,
		},
		{Row: 16, Col: 22}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -53.4375},
			Land: 0.9902202486991882,
			Load: 0,
		},
		{Row: 16, Col: 23}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -47.8125},
			Land: 0.9843831658363342,
			Load: 0,
		},
		{Row: 16, Col: 24}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -42.1875},
			Land: 0.9834408164024353,
			Load: 0,
		},
		{Row: 16, Col: 25}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: -36.5625},
			Land: 0.7029112577438354,
			Load: 0,
		},
		{Row: 16, Col: 34}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 14.0625},
			Land: 0.7291461229324341,
			Load: 0,
		},
		{Row: 16, Col: 35}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 19.6875},
			Land: 0.9912801384925842,
			Load: 0,
		},
		{Row: 16, Col: 36}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 25.3125},
			Land: 0.9837321043014526,
			Load: 0,
		},
		{Row: 16, Col: 37}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 30.9375},
			Land: 0.8985360860824585,
			Load: 0,
		},
		{Row: 16, Col: 38}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 36.5625},
			Land: 0.9624176621437073,
			Load: 0,
		},
		{Row: 16, Col: 51}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 109.6875},
			Land: 0.23714911937713623,
			Load: 0,
		},
		{Row: 16, Col: 56}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 137.8125},
			Land: 0.3253336548805237,
			Load: 0,
		},
		{Row: 16, Col: 57}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 143.4375},
			Land: 0.701079249382019,
			Load: 0,
		},
		{Row: 16, Col: 58}: {
			S2:   dotworld.S2{Lat: -7.20703125, Long: 149.0625},
			Land: 0.30998700857162476,
			Load: 0,
		},
		{Row: 17, Col: 18}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -75.9375},
			Land: 0.623881459236145,
			Load: 0,
		},
		{Row: 17, Col: 19}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -70.3125},
			Land: 0.9863118529319763,
			Load: 0,
		},
		{Row: 17, Col: 20}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -64.6875},
			Land: 0.9791743159294128,
			Load: 0,
		},
		{Row: 17, Col: 21}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -59.0625},
			Land: 0.9939855337142944,
			Load: 0,
		},
		{Row: 17, Col: 22}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -53.4375},
			Land: 0.9905728101730347,
			Load: 0,
		},
		{Row: 17, Col: 23}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -47.8125},
			Land: 0.9946437478065491,
			Load: 0,
		},
		{Row: 17, Col: 24}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -42.1875},
			Land: 0.985541820526123,
			Load: 0,
		},
		{Row: 17, Col: 25}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: -36.5625},
			Land: 0.22284317016601562,
			Load: 0,
		},
		{Row: 17, Col: 34}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 14.0625},
			Land: 0.6857151389122009,
			Load: 0,
		},
		{Row: 17, Col: 35}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 19.6875},
			Land: 0.9937657713890076,
			Load: 0,
		},
		{Row: 17, Col: 36}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 25.3125},
			Land: 0.9892192482948303,
			Load: 0,
		},
		{Row: 17, Col: 37}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 30.9375},
			Land: 0.9852254390716553,
			Load: 0,
		},
		{Row: 17, Col: 38}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 36.5625},
			Land: 0.9231014251708984,
			Load: 0,
		},
		{Row: 17, Col: 39}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 42.1875},
			Land: 0.2114061713218689,
			Load: 0,
		},
		{Row: 17, Col: 40}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 47.8125},
			Land: 0.2262987494468689,
			Load: 0,
		},
		{Row: 17, Col: 55}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 132.1875},
			Land: 0.616977334022522,
			Load: 0,
		},
		{Row: 17, Col: 57}: {
			S2:   dotworld.S2{Lat: -12.83203125, Long: 143.4375},
			Land: 0.3150467276573181,
			Load: 0,
		},
		{Row: 18, Col: 19}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: -70.3125},
			Land: 0.6208850145339966,
			Load: 0,
		},
		{Row: 18, Col: 20}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: -64.6875},
			Land: 0.988869845867157,
			Load: 0,
		},
		{Row: 18, Col: 21}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: -59.0625},
			Land: 0.9922126531600952,
			Load: 0,
		},
		{Row: 18, Col: 22}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: -53.4375},
			Land: 0.9883135557174683,
			Load: 0,
		},
		{Row: 18, Col: 23}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: -47.8125},
			Land: 0.9789131879806519,
			Load: 0,
		},
		{Row: 18, Col: 24}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: -42.1875},
			Land: 0.9197653532028198,
			Load: 0,
		},
		{Row: 18, Col: 34}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 14.0625},
			Land: 0.7972285151481628,
			Load: 0,
		},
		{Row: 18, Col: 35}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 19.6875},
			Land: 0.9967464804649353,
			Load: 0,
		},
		{Row: 18, Col: 36}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 25.3125},
			Land: 0.9866505265235901,
			Load: 0,
		},
		{Row: 18, Col: 37}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 30.9375},
			Land: 0.9837536215782166,
			Load: 0,
		},
		{Row: 18, Col: 38}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 36.5625},
			Land: 0.5381467342376709,
			Load: 0,
		},
		{Row: 18, Col: 40}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 47.8125},
			Land: 0.7336511611938477,
			Load: 0,
		},
		{Row: 18, Col: 53}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 120.9375},
			Land: 0.4261512756347656,
			Load: 0,
		},
		{Row: 18, Col: 54}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 126.5625},
			Land: 0.9786324501037598,
			Load: 0,
		},
		{Row: 18, Col: 55}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 132.1875},
			Land: 0.9999851584434509,
			Load: 0,
		},
		{Row: 18, Col: 56}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 137.8125},
			Land: 0.8585221767425537,
			Load: 0,
		},
		{Row: 18, Col: 57}: {
			S2:   dotworld.S2{Lat: -18.45703125, Long: 143.4375},
			Land: 0.9282228946685791,
			Load: 0,
		},
		{Row: 19, Col: 19}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: -70.3125},
			Land: 0.5283411741256714,
			Load: 0,
		},
		{Row: 19, Col: 20}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: -64.6875},
			Land: 0.9940951466560364,
			Load: 0,
		},
		{Row: 19, Col: 21}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: -59.0625},
			Land: 0.9871606230735779,
			Load: 0,
		},
		{Row: 19, Col: 22}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: -53.4375},
			Land: 0.9817138910293579,
			Load: 0,
		},
		{Row: 19, Col: 23}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: -47.8125},
			Land: 0.7012676000595093,
			Load: 0,
		},
		{Row: 19, Col: 34}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 14.0625},
			Land: 0.40837353467941284,
			Load: 0,
		},
		{Row: 19, Col: 35}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 19.6875},
			Land: 0.9999064207077026,
			Load: 0,
		},
		{Row: 19, Col: 36}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 25.3125},
			Land: 0.9979721903800964,
			Load: 0,
		},
		{Row: 19, Col: 37}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 30.9375},
			Land: 0.9449031949043274,
			Load: 0,
		},
		{Row: 19, Col: 40}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 47.8125},
			Land: 0.33993732929229736,
			Load: 0,
		},
		{Row: 19, Col: 52}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 115.3125},
			Land: 0.7521740198135376,
			Load: 0,
		},
		{Row: 19, Col: 53}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 120.9375},
			Land: 1,
			Load: 0,
		},
		{Row: 19, Col: 54}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 126.5625},
			Land: 1,
			Load: 0,
		},
		{Row: 19, Col: 55}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 132.1875},
			Land: 1,
			Load: 0,
		},
		{Row: 19, Col: 56}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 137.8125},
			Land: 0.9999298453330994,
			Load: 0,
		},
		{Row: 19, Col: 57}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 143.4375},
			Land: 0.9998039603233337,
			Load: 0,
		},
		{Row: 19, Col: 58}: {
			S2:   dotworld.S2{Lat: -24.08203125, Long: 149.0625},
			Land: 0.8703991174697876,
			Load: 0,
		},
		{Row: 20, Col: 19}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: -70.3125},
			Land: 0.6877120733261108,
			Load: 0,
		},
		{Row: 20, Col: 20}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: -64.6875},
			Land: 0.9844159483909607,
			Load: 0,
		},
		{Row: 20, Col: 21}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: -59.0625},
			Land: 0.9779385328292847,
			Load: 0,
		},
		{Row: 20, Col: 22}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: -53.4375},
			Land: 0.9127402901649475,
			Load: 0,
		},
		{Row: 20, Col: 35}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 19.6875},
			Land: 0.9160252213478088,
			Load: 0,
		},
		{Row: 20, Col: 36}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 25.3125},
			Land: 0.9895464777946472,
			Load: 0,
		},
		{Row: 20, Col: 37}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 30.9375},
			Land: 0.5249125957489014,
			Load: 0,
		},
		{Row: 20, Col: 52}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 115.3125},
			Land: 0.5741277933120728,
			Load: 0,
		},
		{Row: 20, Col: 53}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 120.9375},
			Land: 1,
			Load: 0,
		},
		{Row: 20, Col: 54}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 126.5625},
			Land: 0.9471030831336975,
			Load: 0,
		},
		{Row: 20, Col: 55}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 132.1875},
			Land: 0.8935123085975647,
			Load: 0,
		},
		{Row: 20, Col: 56}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 137.8125},
			Land: 0.9998661875724792,
			Load: 0,
		},
		{Row: 20, Col: 57}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 143.4375},
			Land: 0.9960190653800964,
			Load: 0,
		},
		{Row: 20, Col: 58}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 149.0625},
			Land: 0.9937545657157898,
			Load: 0,
		},
		{Row: 20, Col: 59}: {
			S2:   dotworld.S2{Lat: -29.70703125, Long: 154.6875},
			Land: 0.2274957299232483,
			Load: 0,
		},
		{Row: 21, Col: 19}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: -70.3125},
			Land: 0.870190441608429,
			Load: 0,
		},
		{Row: 21, Col: 20}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: -64.6875},
			Land: 0.9943161010742188,
			Load: 0,
		},
		{Row: 21, Col: 21}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: -59.0625},
			Land: 0.8652269840240479,
			Load: 0,
		},
		{Row: 21, Col: 22}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: -53.4375},
			Land: 0.2017410397529602,
			Load: 0,
		},
		{Row: 21, Col: 35}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 19.6875},
			Land: 0.2513219714164734,
			Load: 0,
		},
		{Row: 21, Col: 36}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 25.3125},
			Land: 0.22156888246536255,
			Load: 0,
		},
		{Row: 21, Col: 52}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 115.3125},
			Land: 0.20354384183883667,
			Load: 0,
		},
		{Row: 21, Col: 53}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 120.9375},
			Land: 0.27368760108947754,
			Load: 0,
		},
		{Row: 21, Col: 56}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 137.8125},
			Land: 0.46574705839157104,
			Load: 0,
		},
		{Row: 21, Col: 57}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 143.4375},
			Land: 0.9832876324653625,
			Load: 0,
		},
		{Row: 21, Col: 58}: {
			S2:   dotworld.S2{Lat: -35.33203125, Long: 149.0625},
			Land: 0.7434965372085571,
			Load: 0,
		},
		{Row: 22, Col: 19}: {
			S2:   dotworld.S2{Lat: -40.95703125, Long: -70.3125},
			Land: 0.9574846029281616,
			Load: 0,
		},
		{Row: 22, Col: 20}: {
			S2:   dotworld.S2{Lat: -40.95703125, Long: -64.6875},
			Land: 0.7121213674545288,
			Load: 0,
		},
		{Row: 22, Col: 62}: {
			S2:   dotworld.S2{Lat: -40.95703125, Long: 171.5625},
			Land: 0.23981189727783203,
			Load: 0,
		},
		{Row: 22, Col: 63}: {
			S2:   dotworld.S2{Lat: -40.95703125, Long: 177.1875},
			Land: 0.23275625705718994,
			Load: 0,
		},
		{Row: 23, Col: 18}: {
			S2:   dotworld.S2{Lat: -46.58203125, Long: -75.9375},
			Land: 0.2569788098335266,
			Load: 0,
		},
		{Row: 23, Col: 19}: {
			S2:   dotworld.S2{Lat: -46.58203125, Long: -70.3125},
			Land: 0.9642609357833862,
			Load: 0,
		},
		{Row: 24, Col: 19}: {
			S2:   dotworld.S2{Lat: -52.20703125, Long: -70.3125},
			Land: 0.6998836994171143,
			Load: 0,
		},
	},
}
